run:
  go: "1.21"
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocognit
    - govet
    - ineffassign
    - typecheck
    - varcheck
    - asciicheck
    - dogsled
    - exhaustive
    - exportloopref
    - errorlint
    - durationcheck
    - gofmt
    - goprintffuncname
    - nestif
    - makezero
    - prealloc
    - predeclared
    - unconvert
