version-file = "internal/version/version"

# hook scripts
[hooks]

# git hook pre push
pre-push = [
    "echo 'golangci-lint run'",
    "golangci-lint run",
    "echo 'go test ./parallelenv_test.go'",
    "go test ./parallelenv_test.go",
]
